# إعدادات موقع قمة التميز
title: "قمة التميز للاستشارات المالية والادارية"
email: "contact@gimahpro.com"
description: >-
  قمة التميز للاستشارات المالية والإدارية، نقدم حلولاً احترافية
  لدعم نمو الشركات وتحقيق رؤية السعودية 2030.

baseurl: ""
url: "https://www.gimahpro.com"

# الروابط الدائمة للمقالات (بدون .html)
permalink: /blog/:title/

# تفعيل الإخراج للمقالات
collections:
  posts:
    output: true

# إضافة البلجن الخاص بالسيت ماب
plugins:
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
