# إعدادات موقع قمة التميز
title:  قمة التميز للاستشارات المالية والادارية 
email: contact@gimahpro.com
description: >-
   قمة التميز للاستشارات المالية والإدارية، نقدم حلولاً احترافية
  لدعم نمو الشركات وتحقيق رؤية السعودية 2030.

baseurl: "" 
url: "https://www.gimahpro.com"

# التعديل الذهبي هنا:
permalink: /blog/:title.html

# إعدادات إضافية لضمان قراءة المقالات
collections:
  posts:
    output: true

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
